version: "3"
services: 
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "url"
    ports: 
      - 5432:5432
    volumes:
      - ./resources/sql:/docker-entrypoint-initdb.d
